// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.2
// source: proto/copier.proto

package copierpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CopierService_Start_FullMethodName  = "/copier.CopierService/Start"
	CopierService_List_FullMethodName   = "/copier.CopierService/List"
	CopierService_Pause_FullMethodName  = "/copier.CopierService/Pause"
	CopierService_Remove_FullMethodName = "/copier.CopierService/Remove"
)

// CopierServiceClient is the client API for CopierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Trade copier operations over gRPC.
//
// Credentials (passwords) are strictly carried in the request body over HTTP/2 gRPC,
// preventing plain-text credential leakage in HTTP query parameters, server access logs,
// or proxy routing histories.
type CopierServiceClient interface {
	// Start a trade copier between master and slave accounts.
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartReply, error)
	// List all active and paused copiers belonging to a user.
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
	// Pause or resume an existing copier without deleting configuration.
	Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*SimpleReply, error)
	// Remove a copier and unregister trade hooks.
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*SimpleReply, error)
}

type copierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCopierServiceClient(cc grpc.ClientConnInterface) CopierServiceClient {
	return &copierServiceClient{cc}
}

func (c *copierServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartReply)
	err := c.cc.Invoke(ctx, CopierService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *copierServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReply)
	err := c.cc.Invoke(ctx, CopierService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *copierServiceClient) Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*SimpleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleReply)
	err := c.cc.Invoke(ctx, CopierService_Pause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *copierServiceClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*SimpleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleReply)
	err := c.cc.Invoke(ctx, CopierService_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CopierServiceServer is the server API for CopierService service.
// All implementations must embed UnimplementedCopierServiceServer
// for forward compatibility.
//
// Trade copier operations over gRPC.
//
// Credentials (passwords) are strictly carried in the request body over HTTP/2 gRPC,
// preventing plain-text credential leakage in HTTP query parameters, server access logs,
// or proxy routing histories.
type CopierServiceServer interface {
	// Start a trade copier between master and slave accounts.
	Start(context.Context, *StartRequest) (*StartReply, error)
	// List all active and paused copiers belonging to a user.
	List(context.Context, *ListRequest) (*ListReply, error)
	// Pause or resume an existing copier without deleting configuration.
	Pause(context.Context, *PauseRequest) (*SimpleReply, error)
	// Remove a copier and unregister trade hooks.
	Remove(context.Context, *RemoveRequest) (*SimpleReply, error)
	mustEmbedUnimplementedCopierServiceServer()
}

// UnimplementedCopierServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCopierServiceServer struct{}

func (UnimplementedCopierServiceServer) Start(context.Context, *StartRequest) (*StartReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedCopierServiceServer) List(context.Context, *ListRequest) (*ListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCopierServiceServer) Pause(context.Context, *PauseRequest) (*SimpleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedCopierServiceServer) Remove(context.Context, *RemoveRequest) (*SimpleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedCopierServiceServer) mustEmbedUnimplementedCopierServiceServer() {}
func (UnimplementedCopierServiceServer) testEmbeddedByValue()                       {}

// UnsafeCopierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CopierServiceServer will
// result in compilation errors.
type UnsafeCopierServiceServer interface {
	mustEmbedUnimplementedCopierServiceServer()
}

func RegisterCopierServiceServer(s grpc.ServiceRegistrar, srv CopierServiceServer) {
	// If the following call panics, it indicates UnimplementedCopierServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CopierService_ServiceDesc, srv)
}

func _CopierService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopierServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CopierService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopierServiceServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CopierService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopierServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CopierService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopierServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CopierService_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopierServiceServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CopierService_Pause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopierServiceServer).Pause(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CopierService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopierServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CopierService_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopierServiceServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CopierService_ServiceDesc is the grpc.ServiceDesc for CopierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CopierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "copier.CopierService",
	HandlerType: (*CopierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _CopierService_Start_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CopierService_List_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _CopierService_Pause_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _CopierService_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/copier.proto",
}

const (
	DemoAccount_OpenDemoAccount_FullMethodName = "/copier.DemoAccount/OpenDemoAccount"
)

// DemoAccountClient is the client API for DemoAccount service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Demo account creation service definition
type DemoAccountClient interface {
	// Provision a new MetaTrader demo account on the fly.
	OpenDemoAccount(ctx context.Context, in *GuiDemoOpenAccountRequest, opts ...grpc.CallOption) (*GuiDemoOpenAccountReply, error)
}

type demoAccountClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoAccountClient(cc grpc.ClientConnInterface) DemoAccountClient {
	return &demoAccountClient{cc}
}

func (c *demoAccountClient) OpenDemoAccount(ctx context.Context, in *GuiDemoOpenAccountRequest, opts ...grpc.CallOption) (*GuiDemoOpenAccountReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuiDemoOpenAccountReply)
	err := c.cc.Invoke(ctx, DemoAccount_OpenDemoAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoAccountServer is the server API for DemoAccount service.
// All implementations must embed UnimplementedDemoAccountServer
// for forward compatibility.
//
// Demo account creation service definition
type DemoAccountServer interface {
	// Provision a new MetaTrader demo account on the fly.
	OpenDemoAccount(context.Context, *GuiDemoOpenAccountRequest) (*GuiDemoOpenAccountReply, error)
	mustEmbedUnimplementedDemoAccountServer()
}

// UnimplementedDemoAccountServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDemoAccountServer struct{}

func (UnimplementedDemoAccountServer) OpenDemoAccount(context.Context, *GuiDemoOpenAccountRequest) (*GuiDemoOpenAccountReply, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenDemoAccount not implemented")
}
func (UnimplementedDemoAccountServer) mustEmbedUnimplementedDemoAccountServer() {}
func (UnimplementedDemoAccountServer) testEmbeddedByValue()                     {}

// UnsafeDemoAccountServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DemoAccountServer will
// result in compilation errors.
type UnsafeDemoAccountServer interface {
	mustEmbedUnimplementedDemoAccountServer()
}

func RegisterDemoAccountServer(s grpc.ServiceRegistrar, srv DemoAccountServer) {
	// If the following call panics, it indicates UnimplementedDemoAccountServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DemoAccount_ServiceDesc, srv)
}

func _DemoAccount_OpenDemoAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuiDemoOpenAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoAccountServer).OpenDemoAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DemoAccount_OpenDemoAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoAccountServer).OpenDemoAccount(ctx, req.(*GuiDemoOpenAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DemoAccount_ServiceDesc is the grpc.ServiceDesc for DemoAccount service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DemoAccount_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "copier.DemoAccount",
	HandlerType: (*DemoAccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenDemoAccount",
			Handler:    _DemoAccount_OpenDemoAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/copier.proto",
}
