// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.27.2
// source: proto/copier.proto

package copierpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetaTrader trading account connection descriptor.
type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account protocol type: "MT4" or "MT5".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Account login number / user id.
	User uint64 `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	// Account trading password.
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// Broker terminal server name (e.g. "MetaQuotes-Demo").
	Server string `protobuf:"bytes,4,opt,name=server,proto3" json:"server,omitempty"`
	// Optional friendly label or display name.
	Name          string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_copier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_copier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_copier_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Account) GetUser() uint64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Account) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Parameters to initialize and start real-time trade copying.
type StartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client user key for billing and authorization.
	UserKey string `protobuf:"bytes,1,opt,name=user_key,json=userKey,proto3" json:"user_key,omitempty"`
	// Manager or owner key configuring this copier instance.
	ManagerKey string `protobuf:"bytes,2,opt,name=manager_key,json=managerKey,proto3" json:"manager_key,omitempty"`
	// Source master account whose trades are copied.
	Master *Account `protobuf:"bytes,3,opt,name=master,proto3" json:"master,omitempty"`
	// Target slave account where trades are replicated.
	Slave *Account `protobuf:"bytes,4,opt,name=slave,proto3" json:"slave,omitempty"`
	// Risk calculation model:
	// "FixedLot" | "LotMultiplier" | "BalanceMultiplier" | "FixedBalanceMultiplier" | "EquityMultiplier"
	RiskType string `protobuf:"bytes,5,opt,name=risk_type,json=riskType,proto3" json:"risk_type,omitempty"`
	// Sizing parameter formatted as decimal string (e.g. "1.0", "0.01", "2.5").
	RiskValue string `protobuf:"bytes,6,opt,name=risk_value,json=riskValue,proto3" json:"risk_value,omitempty"`
	// Baseline master balance required when risk_type is "FixedBalanceMultiplier".
	FixedMasterBalance string `protobuf:"bytes,7,opt,name=fixed_master_balance,json=fixedMasterBalance,proto3" json:"fixed_master_balance,omitempty"`
	// Synchronize Stop Loss modifications from master to slave.
	CopySl bool `protobuf:"varint,8,opt,name=copy_sl,json=copySl,proto3" json:"copy_sl,omitempty"`
	// Synchronize Take Profit modifications from master to slave.
	CopyTp bool `protobuf:"varint,9,opt,name=copy_tp,json=copyTp,proto3" json:"copy_tp,omitempty"`
	// Copy pending orders (Buy Limit, Sell Limit, Buy Stop, Sell Stop).
	CopyPendingOrders bool `protobuf:"varint,10,opt,name=copy_pending_orders,json=copyPendingOrders,proto3" json:"copy_pending_orders,omitempty"`
	// Invert order directions: BUY -> SELL and SELL -> BUY.
	ReverseCopy   bool `protobuf:"varint,11,opt,name=reverse_copy,json=reverseCopy,proto3" json:"reverse_copy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_proto_copier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_copier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_proto_copier_proto_rawDescGZIP(), []int{1}
}

func (x *StartRequest) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

func (x *StartRequest) GetManagerKey() string {
	if x != nil {
		return x.ManagerKey
	}
	return ""
}

func (x *StartRequest) GetMaster() *Account {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *StartRequest) GetSlave() *Account {
	if x != nil {
		return x.Slave
	}
	return nil
}

func (x *StartRequest) GetRiskType() string {
	if x != nil {
		return x.RiskType
	}
	return ""
}

func (x *StartRequest) GetRiskValue() string {
	if x != nil {
		return x.RiskValue
	}
	return ""
}

func (x *StartRequest) GetFixedMasterBalance() string {
	if x != nil {
		return x.FixedMasterBalance
	}
	return ""
}

func (x *StartRequest) GetCopySl() bool {
	if x != nil {
		return x.CopySl
	}
	return false
}

func (x *StartRequest) GetCopyTp() bool {
	if x != nil {
		return x.CopyTp
	}
	return false
}

func (x *StartRequest) GetCopyPendingOrders() bool {
	if x != nil {
		return x.CopyPendingOrders
	}
	return false
}

func (x *StartRequest) GetReverseCopy() bool {
	if x != nil {
		return x.ReverseCopy
	}
	return false
}

type StartReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if copier was created and successfully attached.
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Unique copier instance UUID.
	CopierId string `protobuf:"bytes,2,opt,name=copier_id,json=copierId,proto3" json:"copier_id,omitempty"`
	// Descriptive error message if start failed.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartReply) Reset() {
	*x = StartReply{}
	mi := &file_proto_copier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReply) ProtoMessage() {}

func (x *StartReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_copier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReply.ProtoReflect.Descriptor instead.
func (*StartReply) Descriptor() ([]byte, []int) {
	return file_proto_copier_proto_rawDescGZIP(), []int{2}
}

func (x *StartReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StartReply) GetCopierId() string {
	if x != nil {
		return x.CopierId
	}
	return ""
}

func (x *StartReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter copiers belonging to this user key.
	UserKey       string `protobuf:"bytes,1,opt,name=user_key,json=userKey,proto3" json:"user_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_copier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_copier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_copier_proto_rawDescGZIP(), []int{3}
}

func (x *ListRequest) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

// Sanitized copier summary that never exposes trading account passwords.
type CopierSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MasterType    string                 `protobuf:"bytes,2,opt,name=master_type,json=masterType,proto3" json:"master_type,omitempty"`
	MasterUser    uint64                 `protobuf:"varint,3,opt,name=master_user,json=masterUser,proto3" json:"master_user,omitempty"`
	MasterServer  string                 `protobuf:"bytes,4,opt,name=master_server,json=masterServer,proto3" json:"master_server,omitempty"`
	SlaveType     string                 `protobuf:"bytes,5,opt,name=slave_type,json=slaveType,proto3" json:"slave_type,omitempty"`
	SlaveUser     uint64                 `protobuf:"varint,6,opt,name=slave_user,json=slaveUser,proto3" json:"slave_user,omitempty"`
	SlaveServer   string                 `protobuf:"bytes,7,opt,name=slave_server,json=slaveServer,proto3" json:"slave_server,omitempty"`
	RiskType      string                 `protobuf:"bytes,8,opt,name=risk_type,json=riskType,proto3" json:"risk_type,omitempty"`
	RiskValue     string                 `protobuf:"bytes,9,opt,name=risk_value,json=riskValue,proto3" json:"risk_value,omitempty"`
	Paused        bool                   `protobuf:"varint,10,opt,name=paused,proto3" json:"paused,omitempty"`
	PauseReason   string                 `protobuf:"bytes,11,opt,name=pause_reason,json=pauseReason,proto3" json:"pause_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopierSummary) Reset() {
	*x = CopierSummary{}
	mi := &file_proto_copier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopierSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopierSummary) ProtoMessage() {}

func (x *CopierSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_copier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopierSummary.ProtoReflect.Descriptor instead.
func (*CopierSummary) Descriptor() ([]byte, []int) {
	return file_proto_copier_proto_rawDescGZIP(), []int{4}
}

func (x *CopierSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CopierSummary) GetMasterType() string {
	if x != nil {
		return x.MasterType
	}
	return ""
}

func (x *CopierSummary) GetMasterUser() uint64 {
	if x != nil {
		return x.MasterUser
	}
	return 0
}

func (x *CopierSummary) GetMasterServer() string {
	if x != nil {
		return x.MasterServer
	}
	return ""
}

func (x *CopierSummary) GetSlaveType() string {
	if x != nil {
		return x.SlaveType
	}
	return ""
}

func (x *CopierSummary) GetSlaveUser() uint64 {
	if x != nil {
		return x.SlaveUser
	}
	return 0
}

func (x *CopierSummary) GetSlaveServer() string {
	if x != nil {
		return x.SlaveServer
	}
	return ""
}

func (x *CopierSummary) GetRiskType() string {
	if x != nil {
		return x.RiskType
	}
	return ""
}

func (x *CopierSummary) GetRiskValue() string {
	if x != nil {
		return x.RiskValue
	}
	return ""
}

func (x *CopierSummary) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *CopierSummary) GetPauseReason() string {
	if x != nil {
		return x.PauseReason
	}
	return ""
}

type ListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Copiers       []*CopierSummary       `protobuf:"bytes,2,rep,name=copiers,proto3" json:"copiers,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReply) Reset() {
	*x = ListReply{}
	mi := &file_proto_copier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReply) ProtoMessage() {}

func (x *ListReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_copier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReply.ProtoReflect.Descriptor instead.
func (*ListReply) Descriptor() ([]byte, []int) {
	return file_proto_copier_proto_rawDescGZIP(), []int{5}
}

func (x *ListReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ListReply) GetCopiers() []*CopierSummary {
	if x != nil {
		return x.Copiers
	}
	return nil
}

func (x *ListReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PauseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserKey       string                 `protobuf:"bytes,1,opt,name=user_key,json=userKey,proto3" json:"user_key,omitempty"`
	CopierId      string                 `protobuf:"bytes,2,opt,name=copier_id,json=copierId,proto3" json:"copier_id,omitempty"`
	Paused        bool                   `protobuf:"varint,3,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRequest) Reset() {
	*x = PauseRequest{}
	mi := &file_proto_copier_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRequest) ProtoMessage() {}

func (x *PauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_copier_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRequest.ProtoReflect.Descriptor instead.
func (*PauseRequest) Descriptor() ([]byte, []int) {
	return file_proto_copier_proto_rawDescGZIP(), []int{6}
}

func (x *PauseRequest) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

func (x *PauseRequest) GetCopierId() string {
	if x != nil {
		return x.CopierId
	}
	return ""
}

func (x *PauseRequest) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserKey       string                 `protobuf:"bytes,1,opt,name=user_key,json=userKey,proto3" json:"user_key,omitempty"`
	CopierId      string                 `protobuf:"bytes,2,opt,name=copier_id,json=copierId,proto3" json:"copier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_proto_copier_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_copier_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_copier_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveRequest) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

func (x *RemoveRequest) GetCopierId() string {
	if x != nil {
		return x.CopierId
	}
	return ""
}

type SimpleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleReply) Reset() {
	*x = SimpleReply{}
	mi := &file_proto_copier_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleReply) ProtoMessage() {}

func (x *SimpleReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_copier_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleReply.ProtoReflect.Descriptor instead.
func (*SimpleReply) Descriptor() ([]byte, []int) {
	return file_proto_copier_proto_rawDescGZIP(), []int{8}
}

func (x *SimpleReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SimpleReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GuiDemoOpenAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Company        string                 `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	FirstName      string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email          string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone          string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Server         string                 `protobuf:"bytes,6,opt,name=server,proto3" json:"server,omitempty"`
	AccountType    string                 `protobuf:"bytes,7,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GuiDemoOpenAccountRequest) Reset() {
	*x = GuiDemoOpenAccountRequest{}
	mi := &file_proto_copier_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuiDemoOpenAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiDemoOpenAccountRequest) ProtoMessage() {}

func (x *GuiDemoOpenAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_copier_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiDemoOpenAccountRequest.ProtoReflect.Descriptor instead.
func (*GuiDemoOpenAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_copier_proto_rawDescGZIP(), []int{9}
}

func (x *GuiDemoOpenAccountRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *GuiDemoOpenAccountRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GuiDemoOpenAccountRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *GuiDemoOpenAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GuiDemoOpenAccountRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GuiDemoOpenAccountRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *GuiDemoOpenAccountRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *GuiDemoOpenAccountRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type GuiDemoOpenAccountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	Login         uint64                 `protobuf:"varint,2,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Investor      string                 `protobuf:"bytes,4,opt,name=investor,proto3" json:"investor,omitempty"`
	Server        string                 `protobuf:"bytes,5,opt,name=server,proto3" json:"server,omitempty"`
	DebugLog      string                 `protobuf:"bytes,6,opt,name=debug_log,json=debugLog,proto3" json:"debug_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuiDemoOpenAccountReply) Reset() {
	*x = GuiDemoOpenAccountReply{}
	mi := &file_proto_copier_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuiDemoOpenAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiDemoOpenAccountReply) ProtoMessage() {}

func (x *GuiDemoOpenAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_copier_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiDemoOpenAccountReply.ProtoReflect.Descriptor instead.
func (*GuiDemoOpenAccountReply) Descriptor() ([]byte, []int) {
	return file_proto_copier_proto_rawDescGZIP(), []int{10}
}

func (x *GuiDemoOpenAccountReply) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *GuiDemoOpenAccountReply) GetLogin() uint64 {
	if x != nil {
		return x.Login
	}
	return 0
}

func (x *GuiDemoOpenAccountReply) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GuiDemoOpenAccountReply) GetInvestor() string {
	if x != nil {
		return x.Investor
	}
	return ""
}

func (x *GuiDemoOpenAccountReply) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *GuiDemoOpenAccountReply) GetDebugLog() string {
	if x != nil {
		return x.DebugLog
	}
	return ""
}

var File_proto_copier_proto protoreflect.FileDescriptor

const file_proto_copier_proto_rawDesc = "" +
	"\n" +
	"\x12proto/copier.proto\x12\x06copier\"y\n" +
	"\aAccount\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04user\x18\x02 \x01(\x04R\x04user\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x16\n" +
	"\x06server\x18\x04 \x01(\tR\x06server\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"\x8d\x03\n" +
	"\fStartRequest\x12\x19\n" +
	"\buser_key\x18\x01 \x01(\tR\auserKey\x12\x1f\n" +
	"\vmanager_key\x18\x02 \x01(\tR\n" +
	"managerKey\x12'\n" +
	"\x06master\x18\x03 \x01(\v2\x0f.copier.AccountR\x06master\x12%\n" +
	"\x05slave\x18\x04 \x01(\v2\x0f.copier.AccountR\x05slave\x12\x1b\n" +
	"\trisk_type\x18\x05 \x01(\tR\briskType\x12\x1d\n" +
	"\n" +
	"risk_value\x18\x06 \x01(\tR\triskValue\x120\n" +
	"\x14fixed_master_balance\x18\a \x01(\tR\x12fixedMasterBalance\x12\x17\n" +
	"\acopy_sl\x18\b \x01(\bR\x06copySl\x12\x17\n" +
	"\acopy_tp\x18\t \x01(\bR\x06copyTp\x12.\n" +
	"\x13copy_pending_orders\x18\n" +
	" \x01(\bR\x11copyPendingOrders\x12!\n" +
	"\freverse_copy\x18\v \x01(\bR\vreverseCopy\"O\n" +
	"\n" +
	"StartReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\tcopier_id\x18\x02 \x01(\tR\bcopierId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"(\n" +
	"\vListRequest\x12\x19\n" +
	"\buser_key\x18\x01 \x01(\tR\auserKey\"\xde\x02\n" +
	"\rCopierSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmaster_type\x18\x02 \x01(\tR\n" +
	"masterType\x12\x1f\n" +
	"\vmaster_user\x18\x03 \x01(\x04R\n" +
	"masterUser\x12#\n" +
	"\rmaster_server\x18\x04 \x01(\tR\fmasterServer\x12\x1d\n" +
	"\n" +
	"slave_type\x18\x05 \x01(\tR\tslaveType\x12\x1d\n" +
	"\n" +
	"slave_user\x18\x06 \x01(\x04R\tslaveUser\x12!\n" +
	"\fslave_server\x18\a \x01(\tR\vslaveServer\x12\x1b\n" +
	"\trisk_type\x18\b \x01(\tR\briskType\x12\x1d\n" +
	"\n" +
	"risk_value\x18\t \x01(\tR\triskValue\x12\x16\n" +
	"\x06paused\x18\n" +
	" \x01(\bR\x06paused\x12!\n" +
	"\fpause_reason\x18\v \x01(\tR\vpauseReason\"b\n" +
	"\tListReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12/\n" +
	"\acopiers\x18\x02 \x03(\v2\x15.copier.CopierSummaryR\acopiers\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"^\n" +
	"\fPauseRequest\x12\x19\n" +
	"\buser_key\x18\x01 \x01(\tR\auserKey\x12\x1b\n" +
	"\tcopier_id\x18\x02 \x01(\tR\bcopierId\x12\x16\n" +
	"\x06paused\x18\x03 \x01(\bR\x06paused\"G\n" +
	"\rRemoveRequest\x12\x19\n" +
	"\buser_key\x18\x01 \x01(\tR\auserKey\x12\x1b\n" +
	"\tcopier_id\x18\x02 \x01(\tR\bcopierId\"3\n" +
	"\vSimpleReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x81\x02\n" +
	"\x19GuiDemoOpenAccountRequest\x12\x18\n" +
	"\acompany\x18\x01 \x01(\tR\acompany\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x16\n" +
	"\x06server\x18\x06 \x01(\tR\x06server\x12!\n" +
	"\faccount_type\x18\a \x01(\tR\vaccountType\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x05R\x0etimeoutSeconds\"\xbd\x01\n" +
	"\x17GuiDemoOpenAccountReply\x12\x1f\n" +
	"\vresult_code\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x14\n" +
	"\x05login\x18\x02 \x01(\x04R\x05login\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1a\n" +
	"\binvestor\x18\x04 \x01(\tR\binvestor\x12\x16\n" +
	"\x06server\x18\x05 \x01(\tR\x06server\x12\x1b\n" +
	"\tdebug_log\x18\x06 \x01(\tR\bdebugLog2\xdc\x01\n" +
	"\rCopierService\x121\n" +
	"\x05Start\x12\x14.copier.StartRequest\x1a\x12.copier.StartReply\x12.\n" +
	"\x04List\x12\x13.copier.ListRequest\x1a\x11.copier.ListReply\x122\n" +
	"\x05Pause\x12\x14.copier.PauseRequest\x1a\x13.copier.SimpleReply\x124\n" +
	"\x06Remove\x12\x15.copier.RemoveRequest\x1a\x13.copier.SimpleReply2d\n" +
	"\vDemoAccount\x12U\n" +
	"\x0fOpenDemoAccount\x12!.copier.GuiDemoOpenAccountRequest\x1a\x1f.copier.GuiDemoOpenAccountReplyB>Z+github.com/MetaRPC/GoCopier/copier/copierpb\xaa\x02\x0etradecopy.Grpcb\x06proto3"

var (
	file_proto_copier_proto_rawDescOnce sync.Once
	file_proto_copier_proto_rawDescData []byte
)

func file_proto_copier_proto_rawDescGZIP() []byte {
	file_proto_copier_proto_rawDescOnce.Do(func() {
		file_proto_copier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_copier_proto_rawDesc), len(file_proto_copier_proto_rawDesc)))
	})
	return file_proto_copier_proto_rawDescData
}

var file_proto_copier_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_copier_proto_goTypes = []any{
	(*Account)(nil),                   // 0: copier.Account
	(*StartRequest)(nil),              // 1: copier.StartRequest
	(*StartReply)(nil),                // 2: copier.StartReply
	(*ListRequest)(nil),               // 3: copier.ListRequest
	(*CopierSummary)(nil),             // 4: copier.CopierSummary
	(*ListReply)(nil),                 // 5: copier.ListReply
	(*PauseRequest)(nil),              // 6: copier.PauseRequest
	(*RemoveRequest)(nil),             // 7: copier.RemoveRequest
	(*SimpleReply)(nil),               // 8: copier.SimpleReply
	(*GuiDemoOpenAccountRequest)(nil), // 9: copier.GuiDemoOpenAccountRequest
	(*GuiDemoOpenAccountReply)(nil),   // 10: copier.GuiDemoOpenAccountReply
}
var file_proto_copier_proto_depIdxs = []int32{
	0,  // 0: copier.StartRequest.master:type_name -> copier.Account
	0,  // 1: copier.StartRequest.slave:type_name -> copier.Account
	4,  // 2: copier.ListReply.copiers:type_name -> copier.CopierSummary
	1,  // 3: copier.CopierService.Start:input_type -> copier.StartRequest
	3,  // 4: copier.CopierService.List:input_type -> copier.ListRequest
	6,  // 5: copier.CopierService.Pause:input_type -> copier.PauseRequest
	7,  // 6: copier.CopierService.Remove:input_type -> copier.RemoveRequest
	9,  // 7: copier.DemoAccount.OpenDemoAccount:input_type -> copier.GuiDemoOpenAccountRequest
	2,  // 8: copier.CopierService.Start:output_type -> copier.StartReply
	5,  // 9: copier.CopierService.List:output_type -> copier.ListReply
	8,  // 10: copier.CopierService.Pause:output_type -> copier.SimpleReply
	8,  // 11: copier.CopierService.Remove:output_type -> copier.SimpleReply
	10, // 12: copier.DemoAccount.OpenDemoAccount:output_type -> copier.GuiDemoOpenAccountReply
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_copier_proto_init() }
func file_proto_copier_proto_init() {
	if File_proto_copier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_copier_proto_rawDesc), len(file_proto_copier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_copier_proto_goTypes,
		DependencyIndexes: file_proto_copier_proto_depIdxs,
		MessageInfos:      file_proto_copier_proto_msgTypes,
	}.Build()
	File_proto_copier_proto = out.File
	file_proto_copier_proto_goTypes = nil
	file_proto_copier_proto_depIdxs = nil
}
